spring:
  application:
    name: eventhub
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb+srv://abhi:abhi123@cluster0.jaoirfq.mongodb.net/eventdb?retryWrites=true&w=majority
server:
  port: 8080



app:
  jwtSecret: CampusArenaSecretKeyCampusArenaSecretKeyCampusArenaSecretKeyCampusArenaSecretKey
  jwtExpirationMs: 86400000

file:
  upload-dir: uploads
  max-size: 2097152 # 2MB

cloudinary:
  cloud-name: dixwsvwfk
  api-key: 373627216171653
  api-secret: JOect5FwDTL5eP8IJzWarnzl8TY
